const assert = require('node:assert/strict');
const release = require('./pages-release.cjs');
const commit = 'a'.repeat(40);
const files = { '/index.html': 'reviewed', '/old.css': 'old' };
const live = { id: 'recorded', files, deployment_trigger: { metadata: { branch: 'main', commit_dirty: false, commit_hash: commit } } };
const receipt = { id: live.id, commit, manifest_sha256: release.manifestDigest(files) };
release.assertProvenance(live, files, true, receipt);
assert.throws(() => release.assertProvenance({ ...live, id: 'unknown' }, files, true, receipt));
assert.throws(() => release.assertProvenance({ ...live, files: { ...files, '/index.html': 'drift' } }, files, true, receipt));
assert.throws(() => release.assertProvenance(live, files, false, receipt));
assert.throws(() => release.assertProvenance({ ...live, deployment_trigger: { metadata: { ...live.deployment_trigger.metadata, commit_dirty: true } } }, files, true, receipt));
assert.throws(() => release.assertProvenance({ ...live, deployment_trigger: { metadata: { ...live.deployment_trigger.metadata, branch: 'other' } } }, files, true, receipt));
assert.throws(() => release.assertProvenance({ ...live, deployment_trigger: { metadata: { branch: 'main', commit_dirty: false, commit_hash: '' } } }, files, true, receipt));
assert.throws(() => release.assertProvenance(live, files, true, null));
release.approvedRemovals([{ name: 'old.css' }], [], [{ path: '/old.css', change: 'removed' }]);
assert.throws(() => release.approvedRemovals([{ name: 'old.css' }], [{ name: 'old.css' }], [{ path: '/old.css', change: 'removed' }]));
release.validateApproval([{ name: 'index.html', hash: 'approved' }], { 'index.html': 'approved' });
assert.throws(() => release.validateApproval([{ name: 'index.html', hash: 'changed' }], { 'index.html': 'approved' }));
assert.throws(() => release.validateApproval([{ name: 'new.html', hash: 'new' }], {}));
assert.equal(release.excluded('.github/deploy/release-policy.json'), true);
assert.equal(release.excluded('hero-v2.css?v=20260912-matched-tag.css'), false);
assert.deepEqual(release.differences({ '/index.html': 'old' }, { '/index.html': 'new', '/new.css': 'new' }), [{ path: '/index.html', change: 'changed' }, { path: '/new.css', change: 'added' }]);
console.log('Release provenance, approval, drift, deletion, and file-diff checks passed.');
